name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver
    - name: Start Chrome Driver
      run: |
        chmod -R 0755 vendor/laravel/dusk/bin
        ./vendor/laravel/dusk/bin/chromedriver-linux --version
        ./vendor/laravel/dusk/bin/chromedriver-linux
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Run Dusk Tests
      run: php artisan dusk
